# .github/workflows/deploy.yml
name: Deploy to Cloud Run from Source
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-west1
  SA_KEY_JSON: ${{ secrets.GCP_CREDENTIALS }}

jobs:

  unit-test:
    runs-on: ubuntu-latest
    name: Unit Test
    steps:
      - name:
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python3 -m unittest discover

  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Deploy to Cloud Run from Source
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If required, update to the appropriate source folder
          source: ./

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

  validation-test:
    runs-on: ubuntu-latest
    name: Validation Test
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test REST Endpoint
        run: |
          RESPONSE=$(curl --write-out '%{http_code}' --silent --output /dev/null https://gcpflaskstarter-441218-424364818714.us-west1.run.app)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "REST endpoint returned status code $RESPONSE"
            exit 1
          fi